### DISCUSSION TITLE
Reports for DILG

### DISCUSSION THREAD

**Discussion by jmarkfen** [BSIT-Caprock/barangay-system#102] [Ideas]
Create tables and forms for reporting to DILG.

# DILG

### Accomplishment Report

-  no. of meetings
-  higlights of meetings
-  significant accomplishments
-  date (year-month)
-  type: BADAC, BPOC

by:

BADAC - punong barangay
BPOC - chief tanod

### Accomplishment Report

- date conducted
- activities conducted
- before picture
- after picture

by: SB member

### Attendance
- N/A

## First-time Job Seekers

monthly summary
  - month
  - no. of availees
  - ...

first-time job seekers
  - beneficiary/availee
  - age
  - date of birth
  - sex/gender
  - educational level
    - elementary/high school
    - college
    - out of school youth (bool)
  - course

By: secretary

## Road clearing

- N/A

## KP

monthly transmittal
- month
- cases

cases
- no.
- title

**Comment by jmarkfen** [comment]
# First-time Job Seekers

- #103 

## SQL Tables (excluding id/timestamps/soft deletes)

```yaml
educational_levels:
- name

courses:
- name

sex:
- name

first_time_job_seekers:
- last_name
- first_name
- middle_name
- birth_date
- sex_id
- educational_level_id
- course_id
- date_applied
```

## Table Display

- Month, Year
- Last name
- First name
- Middle name
- Age
- Date of birth
- Sex
- Educational Level
- Course
