### DISCUSSION TITLE
Reports for MDRRMO

### DISCUSSION THREAD

**Discussion by jmarkfen** [BSIT-Caprock/barangay-system#104] [Ideas]
References:

https://drive.google.com/drive/u/0/folders/1Nz58HJkW8tFseLCx1buetx8Ydtx_9GkW

**Comment by jmarkfen** [comment]
# Families

![image](https://github.com/BSIT-Caprock/barangay-system/assets/119049235/1b939802-e682-4829-97cb-58a8dd48860c)

```yaml
Family:

  table:
  - location: location (locatable: zone, street)
  - name: name
  - males: members->scopeMale()->count()
  - females: members->scopeFemale()->count()
  - lgbtq: members->scopeLgbtq()->count()
  - age_0_to_6_months: members->scopeAge(...)->count()
  - age_7_months_to_2_years: members->scopeAge(...)->count()
  - age_3_to_5_years: members->scopeAge(...)->count()
  - age_6_to_12_years: members->scopeAge(...)->count()
  - age_13_to_17_years: members->scopeAge(...)->count()
  - age_18_to_59_years: members->scopeAge(...)->count()
  - age_60_years_and_above: members->scopeAge(...)->count()
  - with_disabilities: members->scopeHasDisability()->count()
  - with_diseases: members->scopeHasDisease()->count()
  - pregnant_women: members->scopeIsPregnant()->count()

  form:
  - barangay_id: id
  - locatable: id - (sitio/purok/zone/block/street)
  - name: string

FamilyMember:

  table:
  - last_name: inhabitant->last_name
  - first_name: inhabitant->first_name
  - middle_name: inhabitant->middle-name
  - sex: inhabitant->sex
  - age: inhabitant->age
  - has_disability: has_disability
  - has_disease: has_disease
  - is_pregnant: is_pregnant

  form:
  - family_id: select
  - inhabitant_id: select
  - is_lgbtq: checkbox
  - has_disability: checkbox
  - has_disease: checkbox
  - is_pregnant: checkbox
  - pregnancy_due_date: date
```
