### DISCUSSION TITLE
Reports for MSWDO

### DISCUSSION THREAD

**Discussion by jmarkfen** [BSIT-Caprock/barangay-system#105] [Ideas]
References:

https://drive.google.com/drive/u/0/folders/19rBlvhGlrVNm3v55k-OPzc0cMO5gbRMp

**Comment by jmarkfen** [comment]
# Persons With Disabilities

```yaml
PersonWithDisability:
  
  table:
  
  - full_name: inhabitant->full_name
  - disability: disability (__toString)
  - disability_cause: disability_cause (__toString)
  
  form:

  - inhabitant_id: select
  - disability_id: select
  - disability_cause_id: select
  - date_applied: date
```
